# Generated by Django 3.0.4 on 2020-06-07 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Babies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(default=1)),
                ('note', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='Babies.Baby')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
