# Generated by Django 3.0.4 on 2020-06-08 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Babies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baby',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='baby',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
